# Auto-generated by rlparser CODE mode.
# raymath
# Source: src/raymath.h

from .types import *
from std.ffi import CStringSlice, c_char, c_uchar, c_short, c_ushort, c_int, c_uint, c_long, c_ulong, c_float, c_double, external_call
from std.memory import stack_allocation
from std.collections import InlineArray


comptime TraceLogCallbackSimple = def(log_level: c_int, text: Pointer[c_char, MutUntrackedOrigin]) -> NoneType

def Clamp(value: c_float, min: c_float, max: c_float) -> c_float:
    return external_call["mojo_raymath_Clamp", c_float](value, min, max)

def Lerp(start: c_float, end: c_float, amount: c_float) -> c_float:
    return external_call["mojo_raymath_Lerp", c_float](start, end, amount)

def Normalize(value: c_float, start: c_float, end: c_float) -> c_float:
    return external_call["mojo_raymath_Normalize", c_float](value, start, end)

def Remap(value: c_float, inputStart: c_float, inputEnd: c_float, outputStart: c_float, outputEnd: c_float) -> c_float:
    return external_call["mojo_raymath_Remap", c_float](value, inputStart, inputEnd, outputStart, outputEnd)

def Wrap(value: c_float, min: c_float, max: c_float) -> c_float:
    return external_call["mojo_raymath_Wrap", c_float](value, min, max)

def FloatEquals(x: c_float, y: c_float) -> c_int:
    return external_call["mojo_raymath_FloatEquals", c_int](x, y)

def Vector2Zero() -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2Zero", NoneType](__out)
    return __out[]

def Vector2One() -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2One", NoneType](__out)
    return __out[]

def Vector2Add(v1: Vector2, v2: Vector2) -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2Add", NoneType](Pointer(to=v1), Pointer(to=v2), __out)
    return __out[]

def Vector2AddValue(v: Vector2, add: c_float) -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2AddValue", NoneType](Pointer(to=v), add, __out)
    return __out[]

def Vector2Subtract(v1: Vector2, v2: Vector2) -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2Subtract", NoneType](Pointer(to=v1), Pointer(to=v2), __out)
    return __out[]

def Vector2SubtractValue(v: Vector2, sub: c_float) -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2SubtractValue", NoneType](Pointer(to=v), sub, __out)
    return __out[]

def Vector2Length(v: Vector2) -> c_float:
    return external_call["mojo_raymath_Vector2Length", c_float](Pointer(to=v))

def Vector2LengthSqr(v: Vector2) -> c_float:
    return external_call["mojo_raymath_Vector2LengthSqr", c_float](Pointer(to=v))

def Vector2DotProduct(v1: Vector2, v2: Vector2) -> c_float:
    return external_call["mojo_raymath_Vector2DotProduct", c_float](Pointer(to=v1), Pointer(to=v2))

def Vector2CrossProduct(v1: Vector2, v2: Vector2) -> c_float:
    return external_call["mojo_raymath_Vector2CrossProduct", c_float](Pointer(to=v1), Pointer(to=v2))

def Vector2Distance(v1: Vector2, v2: Vector2) -> c_float:
    return external_call["mojo_raymath_Vector2Distance", c_float](Pointer(to=v1), Pointer(to=v2))

def Vector2DistanceSqr(v1: Vector2, v2: Vector2) -> c_float:
    return external_call["mojo_raymath_Vector2DistanceSqr", c_float](Pointer(to=v1), Pointer(to=v2))

def Vector2Angle(v1: Vector2, v2: Vector2) -> c_float:
    return external_call["mojo_raymath_Vector2Angle", c_float](Pointer(to=v1), Pointer(to=v2))

def Vector2LineAngle(start: Vector2, end: Vector2) -> c_float:
    return external_call["mojo_raymath_Vector2LineAngle", c_float](Pointer(to=start), Pointer(to=end))

def Vector2Scale(v: Vector2, scale: c_float) -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2Scale", NoneType](Pointer(to=v), scale, __out)
    return __out[]

def Vector2Multiply(v1: Vector2, v2: Vector2) -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2Multiply", NoneType](Pointer(to=v1), Pointer(to=v2), __out)
    return __out[]

def Vector2Negate(v: Vector2) -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2Negate", NoneType](Pointer(to=v), __out)
    return __out[]

def Vector2Divide(v1: Vector2, v2: Vector2) -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2Divide", NoneType](Pointer(to=v1), Pointer(to=v2), __out)
    return __out[]

def Vector2Normalize(v: Vector2) -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2Normalize", NoneType](Pointer(to=v), __out)
    return __out[]

def Vector2Transform(v: Vector2, mat: Matrix) -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2Transform", NoneType](Pointer(to=v), Pointer(to=mat), __out)
    return __out[]

def Vector2Lerp(v1: Vector2, v2: Vector2, amount: c_float) -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2Lerp", NoneType](Pointer(to=v1), Pointer(to=v2), amount, __out)
    return __out[]

def Vector2Reflect(v: Vector2, normal: Vector2) -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2Reflect", NoneType](Pointer(to=v), Pointer(to=normal), __out)
    return __out[]

def Vector2Min(v1: Vector2, v2: Vector2) -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2Min", NoneType](Pointer(to=v1), Pointer(to=v2), __out)
    return __out[]

def Vector2Max(v1: Vector2, v2: Vector2) -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2Max", NoneType](Pointer(to=v1), Pointer(to=v2), __out)
    return __out[]

def Vector2Rotate(v: Vector2, angle: c_float) -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2Rotate", NoneType](Pointer(to=v), angle, __out)
    return __out[]

def Vector2MoveTowards(v: Vector2, target: Vector2, maxDistance: c_float) -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2MoveTowards", NoneType](Pointer(to=v), Pointer(to=target), maxDistance, __out)
    return __out[]

def Vector2Invert(v: Vector2) -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2Invert", NoneType](Pointer(to=v), __out)
    return __out[]

def Vector2Clamp(v: Vector2, min: Vector2, max: Vector2) -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2Clamp", NoneType](Pointer(to=v), Pointer(to=min), Pointer(to=max), __out)
    return __out[]

def Vector2ClampValue(v: Vector2, min: c_float, max: c_float) -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2ClampValue", NoneType](Pointer(to=v), min, max, __out)
    return __out[]

def Vector2Equals(p: Vector2, q: Vector2) -> c_int:
    return external_call["mojo_raymath_Vector2Equals", c_int](Pointer(to=p), Pointer(to=q))

def Vector2Refract(v: Vector2, n: Vector2, r: c_float) -> Vector2:
    var __out = stack_allocation[1, Vector2]()
    external_call["mojo_raymath_Vector2Refract", NoneType](Pointer(to=v), Pointer(to=n), r, __out)
    return __out[]

def Vector3Zero() -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3Zero", NoneType](__out)
    return __out[]

def Vector3One() -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3One", NoneType](__out)
    return __out[]

def Vector3Add(v1: Vector3, v2: Vector3) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3Add", NoneType](Pointer(to=v1), Pointer(to=v2), __out)
    return __out[]

def Vector3AddValue(v: Vector3, add: c_float) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3AddValue", NoneType](Pointer(to=v), add, __out)
    return __out[]

def Vector3Subtract(v1: Vector3, v2: Vector3) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3Subtract", NoneType](Pointer(to=v1), Pointer(to=v2), __out)
    return __out[]

def Vector3SubtractValue(v: Vector3, sub: c_float) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3SubtractValue", NoneType](Pointer(to=v), sub, __out)
    return __out[]

def Vector3Scale(v: Vector3, scalar: c_float) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3Scale", NoneType](Pointer(to=v), scalar, __out)
    return __out[]

def Vector3Multiply(v1: Vector3, v2: Vector3) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3Multiply", NoneType](Pointer(to=v1), Pointer(to=v2), __out)
    return __out[]

def Vector3CrossProduct(v1: Vector3, v2: Vector3) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3CrossProduct", NoneType](Pointer(to=v1), Pointer(to=v2), __out)
    return __out[]

def Vector3Perpendicular(v: Vector3) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3Perpendicular", NoneType](Pointer(to=v), __out)
    return __out[]

def Vector3Length(v: Vector3) -> c_float:
    return external_call["mojo_raymath_Vector3Length", c_float](v)

def Vector3LengthSqr(v: Vector3) -> c_float:
    return external_call["mojo_raymath_Vector3LengthSqr", c_float](v)

def Vector3DotProduct(v1: Vector3, v2: Vector3) -> c_float:
    return external_call["mojo_raymath_Vector3DotProduct", c_float](Pointer(to=v1), Pointer(to=v2))

def Vector3Distance(v1: Vector3, v2: Vector3) -> c_float:
    return external_call["mojo_raymath_Vector3Distance", c_float](Pointer(to=v1), Pointer(to=v2))

def Vector3DistanceSqr(v1: Vector3, v2: Vector3) -> c_float:
    return external_call["mojo_raymath_Vector3DistanceSqr", c_float](Pointer(to=v1), Pointer(to=v2))

def Vector3Angle(v1: Vector3, v2: Vector3) -> c_float:
    return external_call["mojo_raymath_Vector3Angle", c_float](Pointer(to=v1), Pointer(to=v2))

def Vector3Negate(v: Vector3) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3Negate", NoneType](Pointer(to=v), __out)
    return __out[]

def Vector3Divide(v1: Vector3, v2: Vector3) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3Divide", NoneType](Pointer(to=v1), Pointer(to=v2), __out)
    return __out[]

def Vector3Normalize(v: Vector3) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3Normalize", NoneType](Pointer(to=v), __out)
    return __out[]

def Vector3Project(v1: Vector3, v2: Vector3) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3Project", NoneType](Pointer(to=v1), Pointer(to=v2), __out)
    return __out[]

def Vector3Reject(v1: Vector3, v2: Vector3) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3Reject", NoneType](Pointer(to=v1), Pointer(to=v2), __out)
    return __out[]

def Vector3OrthoNormalize(v1: Pointer[Vector3, MutUntrackedOrigin], v2: Pointer[Vector3, MutUntrackedOrigin]):
    external_call["mojo_raymath_Vector3OrthoNormalize", NoneType](v1, v2)

def Vector3Transform(v: Vector3, mat: Matrix) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3Transform", NoneType](Pointer(to=v), Pointer(to=mat), __out)
    return __out[]

def Vector3RotateByQuaternion(v: Vector3, q: Quaternion) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3RotateByQuaternion", NoneType](Pointer(to=v), Pointer(to=q), __out)
    return __out[]

def Vector3RotateByAxisAngle(v: Vector3, axis: Vector3, angle: c_float) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3RotateByAxisAngle", NoneType](Pointer(to=v), Pointer(to=axis), angle, __out)
    return __out[]

def Vector3MoveTowards(v: Vector3, target: Vector3, maxDistance: c_float) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3MoveTowards", NoneType](Pointer(to=v), Pointer(to=target), maxDistance, __out)
    return __out[]

def Vector3Lerp(v1: Vector3, v2: Vector3, amount: c_float) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3Lerp", NoneType](Pointer(to=v1), Pointer(to=v2), amount, __out)
    return __out[]

def Vector3CubicHermite(v1: Vector3, tangent1: Vector3, v2: Vector3, tangent2: Vector3, amount: c_float) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3CubicHermite", NoneType](Pointer(to=v1), Pointer(to=tangent1), Pointer(to=v2), Pointer(to=tangent2), amount, __out)
    return __out[]

def Vector3Reflect(v: Vector3, normal: Vector3) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3Reflect", NoneType](Pointer(to=v), Pointer(to=normal), __out)
    return __out[]

def Vector3Min(v1: Vector3, v2: Vector3) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3Min", NoneType](Pointer(to=v1), Pointer(to=v2), __out)
    return __out[]

def Vector3Max(v1: Vector3, v2: Vector3) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3Max", NoneType](Pointer(to=v1), Pointer(to=v2), __out)
    return __out[]

def Vector3Barycenter(p: Vector3, a: Vector3, b: Vector3, c: Vector3) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3Barycenter", NoneType](Pointer(to=p), Pointer(to=a), Pointer(to=b), Pointer(to=c), __out)
    return __out[]

def Vector3Unproject(source: Vector3, projection: Matrix, view: Matrix) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3Unproject", NoneType](Pointer(to=source), Pointer(to=projection), Pointer(to=view), __out)
    return __out[]

def Vector3ToFloatV(v: Vector3) -> float3:
    var __out = stack_allocation[1, float3]()
    external_call["mojo_raymath_Vector3ToFloatV", NoneType](Pointer(to=v), __out)
    return __out[]

def Vector3Invert(v: Vector3) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3Invert", NoneType](Pointer(to=v), __out)
    return __out[]

def Vector3Clamp(v: Vector3, min: Vector3, max: Vector3) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3Clamp", NoneType](Pointer(to=v), Pointer(to=min), Pointer(to=max), __out)
    return __out[]

def Vector3ClampValue(v: Vector3, min: c_float, max: c_float) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3ClampValue", NoneType](Pointer(to=v), min, max, __out)
    return __out[]

def Vector3Equals(p: Vector3, q: Vector3) -> c_int:
    return external_call["mojo_raymath_Vector3Equals", c_int](Pointer(to=p), Pointer(to=q))

def Vector3Refract(v: Vector3, n: Vector3, r: c_float) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_Vector3Refract", NoneType](Pointer(to=v), Pointer(to=n), r, __out)
    return __out[]

def Vector4Zero() -> Vector4:
    var __out = stack_allocation[1, Vector4]()
    external_call["mojo_raymath_Vector4Zero", NoneType](__out)
    return __out[]

def Vector4One() -> Vector4:
    var __out = stack_allocation[1, Vector4]()
    external_call["mojo_raymath_Vector4One", NoneType](__out)
    return __out[]

def Vector4Add(v1: Vector4, v2: Vector4) -> Vector4:
    var __out = stack_allocation[1, Vector4]()
    external_call["mojo_raymath_Vector4Add", NoneType](Pointer(to=v1), Pointer(to=v2), __out)
    return __out[]

def Vector4AddValue(v: Vector4, add: c_float) -> Vector4:
    var __out = stack_allocation[1, Vector4]()
    external_call["mojo_raymath_Vector4AddValue", NoneType](Pointer(to=v), add, __out)
    return __out[]

def Vector4Subtract(v1: Vector4, v2: Vector4) -> Vector4:
    var __out = stack_allocation[1, Vector4]()
    external_call["mojo_raymath_Vector4Subtract", NoneType](Pointer(to=v1), Pointer(to=v2), __out)
    return __out[]

def Vector4SubtractValue(v: Vector4, add: c_float) -> Vector4:
    var __out = stack_allocation[1, Vector4]()
    external_call["mojo_raymath_Vector4SubtractValue", NoneType](Pointer(to=v), add, __out)
    return __out[]

def Vector4Length(v: Vector4) -> c_float:
    return external_call["mojo_raymath_Vector4Length", c_float](Pointer(to=v))

def Vector4LengthSqr(v: Vector4) -> c_float:
    return external_call["mojo_raymath_Vector4LengthSqr", c_float](Pointer(to=v))

def Vector4DotProduct(v1: Vector4, v2: Vector4) -> c_float:
    return external_call["mojo_raymath_Vector4DotProduct", c_float](Pointer(to=v1), Pointer(to=v2))

def Vector4Distance(v1: Vector4, v2: Vector4) -> c_float:
    return external_call["mojo_raymath_Vector4Distance", c_float](Pointer(to=v1), Pointer(to=v2))

def Vector4DistanceSqr(v1: Vector4, v2: Vector4) -> c_float:
    return external_call["mojo_raymath_Vector4DistanceSqr", c_float](Pointer(to=v1), Pointer(to=v2))

def Vector4Scale(v: Vector4, scale: c_float) -> Vector4:
    var __out = stack_allocation[1, Vector4]()
    external_call["mojo_raymath_Vector4Scale", NoneType](Pointer(to=v), scale, __out)
    return __out[]

def Vector4Multiply(v1: Vector4, v2: Vector4) -> Vector4:
    var __out = stack_allocation[1, Vector4]()
    external_call["mojo_raymath_Vector4Multiply", NoneType](Pointer(to=v1), Pointer(to=v2), __out)
    return __out[]

def Vector4Negate(v: Vector4) -> Vector4:
    var __out = stack_allocation[1, Vector4]()
    external_call["mojo_raymath_Vector4Negate", NoneType](Pointer(to=v), __out)
    return __out[]

def Vector4Divide(v1: Vector4, v2: Vector4) -> Vector4:
    var __out = stack_allocation[1, Vector4]()
    external_call["mojo_raymath_Vector4Divide", NoneType](Pointer(to=v1), Pointer(to=v2), __out)
    return __out[]

def Vector4Normalize(v: Vector4) -> Vector4:
    var __out = stack_allocation[1, Vector4]()
    external_call["mojo_raymath_Vector4Normalize", NoneType](Pointer(to=v), __out)
    return __out[]

def Vector4Min(v1: Vector4, v2: Vector4) -> Vector4:
    var __out = stack_allocation[1, Vector4]()
    external_call["mojo_raymath_Vector4Min", NoneType](Pointer(to=v1), Pointer(to=v2), __out)
    return __out[]

def Vector4Max(v1: Vector4, v2: Vector4) -> Vector4:
    var __out = stack_allocation[1, Vector4]()
    external_call["mojo_raymath_Vector4Max", NoneType](Pointer(to=v1), Pointer(to=v2), __out)
    return __out[]

def Vector4Lerp(v1: Vector4, v2: Vector4, amount: c_float) -> Vector4:
    var __out = stack_allocation[1, Vector4]()
    external_call["mojo_raymath_Vector4Lerp", NoneType](Pointer(to=v1), Pointer(to=v2), amount, __out)
    return __out[]

def Vector4MoveTowards(v: Vector4, target: Vector4, maxDistance: c_float) -> Vector4:
    var __out = stack_allocation[1, Vector4]()
    external_call["mojo_raymath_Vector4MoveTowards", NoneType](Pointer(to=v), Pointer(to=target), maxDistance, __out)
    return __out[]

def Vector4Invert(v: Vector4) -> Vector4:
    var __out = stack_allocation[1, Vector4]()
    external_call["mojo_raymath_Vector4Invert", NoneType](Pointer(to=v), __out)
    return __out[]

def Vector4Equals(p: Vector4, q: Vector4) -> c_int:
    return external_call["mojo_raymath_Vector4Equals", c_int](Pointer(to=p), Pointer(to=q))

def MatrixDeterminant(mat: Matrix) -> c_float:
    return external_call["mojo_raymath_MatrixDeterminant", c_float](Pointer(to=mat))

def MatrixTrace(mat: Matrix) -> c_float:
    return external_call["mojo_raymath_MatrixTrace", c_float](Pointer(to=mat))

def MatrixTranspose(mat: Matrix) -> Matrix:
    var __out = stack_allocation[1, Matrix]()
    external_call["mojo_raymath_MatrixTranspose", NoneType](Pointer(to=mat), __out)
    return __out[]

def MatrixInvert(mat: Matrix) -> Matrix:
    var __out = stack_allocation[1, Matrix]()
    external_call["mojo_raymath_MatrixInvert", NoneType](Pointer(to=mat), __out)
    return __out[]

def MatrixIdentity() -> Matrix:
    var __out = stack_allocation[1, Matrix]()
    external_call["mojo_raymath_MatrixIdentity", NoneType](__out)
    return __out[]

def MatrixAdd(left: Matrix, right: Matrix) -> Matrix:
    var __out = stack_allocation[1, Matrix]()
    external_call["mojo_raymath_MatrixAdd", NoneType](Pointer(to=left), Pointer(to=right), __out)
    return __out[]

def MatrixSubtract(left: Matrix, right: Matrix) -> Matrix:
    var __out = stack_allocation[1, Matrix]()
    external_call["mojo_raymath_MatrixSubtract", NoneType](Pointer(to=left), Pointer(to=right), __out)
    return __out[]

def MatrixMultiply(left: Matrix, right: Matrix) -> Matrix:
    var __out = stack_allocation[1, Matrix]()
    external_call["mojo_raymath_MatrixMultiply", NoneType](Pointer(to=left), Pointer(to=right), __out)
    return __out[]

def MatrixMultiplyValue(left: Matrix, value: c_float) -> Matrix:
    var __out = stack_allocation[1, Matrix]()
    external_call["mojo_raymath_MatrixMultiplyValue", NoneType](Pointer(to=left), value, __out)
    return __out[]

def MatrixTranslate(x: c_float, y: c_float, z: c_float) -> Matrix:
    var __out = stack_allocation[1, Matrix]()
    external_call["mojo_raymath_MatrixTranslate", NoneType](x, y, z, __out)
    return __out[]

def MatrixRotate(axis: Vector3, angle: c_float) -> Matrix:
    var __out = stack_allocation[1, Matrix]()
    external_call["mojo_raymath_MatrixRotate", NoneType](Pointer(to=axis), angle, __out)
    return __out[]

def MatrixRotateX(angle: c_float) -> Matrix:
    var __out = stack_allocation[1, Matrix]()
    external_call["mojo_raymath_MatrixRotateX", NoneType](angle, __out)
    return __out[]

def MatrixRotateY(angle: c_float) -> Matrix:
    var __out = stack_allocation[1, Matrix]()
    external_call["mojo_raymath_MatrixRotateY", NoneType](angle, __out)
    return __out[]

def MatrixRotateZ(angle: c_float) -> Matrix:
    var __out = stack_allocation[1, Matrix]()
    external_call["mojo_raymath_MatrixRotateZ", NoneType](angle, __out)
    return __out[]

def MatrixRotateXYZ(angle: Vector3) -> Matrix:
    var __out = stack_allocation[1, Matrix]()
    external_call["mojo_raymath_MatrixRotateXYZ", NoneType](Pointer(to=angle), __out)
    return __out[]

def MatrixRotateZYX(angle: Vector3) -> Matrix:
    var __out = stack_allocation[1, Matrix]()
    external_call["mojo_raymath_MatrixRotateZYX", NoneType](Pointer(to=angle), __out)
    return __out[]

def MatrixScale(x: c_float, y: c_float, z: c_float) -> Matrix:
    var __out = stack_allocation[1, Matrix]()
    external_call["mojo_raymath_MatrixScale", NoneType](x, y, z, __out)
    return __out[]

def MatrixFrustum(left: c_double, right: c_double, bottom: c_double, top: c_double, nearPlane: c_double, farPlane: c_double) -> Matrix:
    var __out = stack_allocation[1, Matrix]()
    external_call["mojo_raymath_MatrixFrustum", NoneType](left, right, bottom, top, nearPlane, farPlane, __out)
    return __out[]

def MatrixPerspective(fovY: c_double, aspect: c_double, nearPlane: c_double, farPlane: c_double) -> Matrix:
    var __out = stack_allocation[1, Matrix]()
    external_call["mojo_raymath_MatrixPerspective", NoneType](fovY, aspect, nearPlane, farPlane, __out)
    return __out[]

def MatrixOrtho(left: c_double, right: c_double, bottom: c_double, top: c_double, nearPlane: c_double, farPlane: c_double) -> Matrix:
    var __out = stack_allocation[1, Matrix]()
    external_call["mojo_raymath_MatrixOrtho", NoneType](left, right, bottom, top, nearPlane, farPlane, __out)
    return __out[]

def MatrixLookAt(eye: Vector3, target: Vector3, up: Vector3) -> Matrix:
    var __out = stack_allocation[1, Matrix]()
    external_call["mojo_raymath_MatrixLookAt", NoneType](Pointer(to=eye), Pointer(to=target), Pointer(to=up), __out)
    return __out[]

def MatrixToFloatV(mat: Matrix) -> float16:
    var __out = stack_allocation[1, float16]()
    external_call["mojo_raymath_MatrixToFloatV", NoneType](Pointer(to=mat), __out)
    return __out[]

def QuaternionAdd(q1: Quaternion, q2: Quaternion) -> Quaternion:
    var __out = stack_allocation[1, Quaternion]()
    external_call["mojo_raymath_QuaternionAdd", NoneType](Pointer(to=q1), Pointer(to=q2), __out)
    return __out[]

def QuaternionAddValue(q: Quaternion, add: c_float) -> Quaternion:
    var __out = stack_allocation[1, Quaternion]()
    external_call["mojo_raymath_QuaternionAddValue", NoneType](Pointer(to=q), add, __out)
    return __out[]

def QuaternionSubtract(q1: Quaternion, q2: Quaternion) -> Quaternion:
    var __out = stack_allocation[1, Quaternion]()
    external_call["mojo_raymath_QuaternionSubtract", NoneType](Pointer(to=q1), Pointer(to=q2), __out)
    return __out[]

def QuaternionSubtractValue(q: Quaternion, sub: c_float) -> Quaternion:
    var __out = stack_allocation[1, Quaternion]()
    external_call["mojo_raymath_QuaternionSubtractValue", NoneType](Pointer(to=q), sub, __out)
    return __out[]

def QuaternionIdentity() -> Quaternion:
    var __out = stack_allocation[1, Quaternion]()
    external_call["mojo_raymath_QuaternionIdentity", NoneType](__out)
    return __out[]

def QuaternionLength(q: Quaternion) -> c_float:
    return external_call["mojo_raymath_QuaternionLength", c_float](Pointer(to=q))

def QuaternionNormalize(q: Quaternion) -> Quaternion:
    var __out = stack_allocation[1, Quaternion]()
    external_call["mojo_raymath_QuaternionNormalize", NoneType](Pointer(to=q), __out)
    return __out[]

def QuaternionInvert(q: Quaternion) -> Quaternion:
    var __out = stack_allocation[1, Quaternion]()
    external_call["mojo_raymath_QuaternionInvert", NoneType](Pointer(to=q), __out)
    return __out[]

def QuaternionMultiply(q1: Quaternion, q2: Quaternion) -> Quaternion:
    var __out = stack_allocation[1, Quaternion]()
    external_call["mojo_raymath_QuaternionMultiply", NoneType](Pointer(to=q1), Pointer(to=q2), __out)
    return __out[]

def QuaternionScale(q: Quaternion, mul: c_float) -> Quaternion:
    var __out = stack_allocation[1, Quaternion]()
    external_call["mojo_raymath_QuaternionScale", NoneType](Pointer(to=q), mul, __out)
    return __out[]

def QuaternionDivide(q1: Quaternion, q2: Quaternion) -> Quaternion:
    var __out = stack_allocation[1, Quaternion]()
    external_call["mojo_raymath_QuaternionDivide", NoneType](Pointer(to=q1), Pointer(to=q2), __out)
    return __out[]

def QuaternionLerp(q1: Quaternion, q2: Quaternion, amount: c_float) -> Quaternion:
    var __out = stack_allocation[1, Quaternion]()
    external_call["mojo_raymath_QuaternionLerp", NoneType](Pointer(to=q1), Pointer(to=q2), amount, __out)
    return __out[]

def QuaternionNlerp(q1: Quaternion, q2: Quaternion, amount: c_float) -> Quaternion:
    var __out = stack_allocation[1, Quaternion]()
    external_call["mojo_raymath_QuaternionNlerp", NoneType](Pointer(to=q1), Pointer(to=q2), amount, __out)
    return __out[]

def QuaternionSlerp(q1: Quaternion, q2: Quaternion, amount: c_float) -> Quaternion:
    var __out = stack_allocation[1, Quaternion]()
    external_call["mojo_raymath_QuaternionSlerp", NoneType](Pointer(to=q1), Pointer(to=q2), amount, __out)
    return __out[]

def QuaternionCubicHermiteSpline(q1: Quaternion, outTangent1: Quaternion, q2: Quaternion, inTangent2: Quaternion, t: c_float) -> Quaternion:
    var __out = stack_allocation[1, Quaternion]()
    external_call["mojo_raymath_QuaternionCubicHermiteSpline", NoneType](Pointer(to=q1), Pointer(to=outTangent1), Pointer(to=q2), Pointer(to=inTangent2), t, __out)
    return __out[]

def QuaternionFromVector3ToVector3(from_: Vector3, to: Vector3) -> Quaternion:
    var __out = stack_allocation[1, Quaternion]()
    external_call["mojo_raymath_QuaternionFromVector3ToVector3", NoneType](Pointer(to=from_), Pointer(to=to), __out)
    return __out[]

def QuaternionFromMatrix(mat: Matrix) -> Quaternion:
    var __out = stack_allocation[1, Quaternion]()
    external_call["mojo_raymath_QuaternionFromMatrix", NoneType](Pointer(to=mat), __out)
    return __out[]

def QuaternionToMatrix(q: Quaternion) -> Matrix:
    var __out = stack_allocation[1, Matrix]()
    external_call["mojo_raymath_QuaternionToMatrix", NoneType](Pointer(to=q), __out)
    return __out[]

def QuaternionFromAxisAngle(axis: Vector3, angle: c_float) -> Quaternion:
    var __out = stack_allocation[1, Quaternion]()
    external_call["mojo_raymath_QuaternionFromAxisAngle", NoneType](Pointer(to=axis), angle, __out)
    return __out[]

def QuaternionToAxisAngle(q: Quaternion, outAxis: Pointer[Vector3, MutUntrackedOrigin], outAngle: Pointer[c_float, MutUntrackedOrigin]):
    external_call["mojo_raymath_QuaternionToAxisAngle", NoneType](Pointer(to=q), outAxis, outAngle)

def QuaternionFromEuler(pitch: c_float, yaw: c_float, roll: c_float) -> Quaternion:
    var __out = stack_allocation[1, Quaternion]()
    external_call["mojo_raymath_QuaternionFromEuler", NoneType](pitch, yaw, roll, __out)
    return __out[]

def QuaternionToEuler(q: Quaternion) -> Vector3:
    var __out = stack_allocation[1, Vector3]()
    external_call["mojo_raymath_QuaternionToEuler", NoneType](Pointer(to=q), __out)
    return __out[]

def QuaternionTransform(q: Quaternion, mat: Matrix) -> Quaternion:
    var __out = stack_allocation[1, Quaternion]()
    external_call["mojo_raymath_QuaternionTransform", NoneType](Pointer(to=q), Pointer(to=mat), __out)
    return __out[]

def QuaternionEquals(p: Quaternion, q: Quaternion) -> c_int:
    return external_call["mojo_raymath_QuaternionEquals", c_int](Pointer(to=p), Pointer(to=q))

def MatrixCompose(translation: Vector3, rotation: Quaternion, scale: Vector3) -> Matrix:
    var __out = stack_allocation[1, Matrix]()
    external_call["mojo_raymath_MatrixCompose", NoneType](Pointer(to=translation), Pointer(to=rotation), Pointer(to=scale), __out)
    return __out[]

def MatrixDecompose(mat: Matrix, translation: Pointer[Vector3, MutUntrackedOrigin], rotation: Pointer[Quaternion, MutUntrackedOrigin], scale: Pointer[Vector3, MutUntrackedOrigin]):
    external_call["mojo_raymath_MatrixDecompose", NoneType](Pointer(to=mat), translation, rotation, scale)

