[workspace]
channels = [
    "https://conda.modular.com/max",
    "https://prefix.dev/conda-forge",
]
name = "random-values"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[dependencies]
mojo_raylib = { path = "../.." }

[tasks.run]
cmd = "mojo build main.mojo -Xlinker -L$CONDA_PREFIX/lib -Xlinker -lmojo_raylib_shim -Xlinker -lraylib -o .pixi/main && .pixi/main"
