/* Auto-generated by rlparser CODE mode. */
#include <stdarg.h>
#include <stdio.h>
#include <stdbool.h>
#include "../vendor/raylib/src/raylib.h"
#define RAYMATH_STATIC_INLINE
#include "../vendor/raylib/src/raymath.h"

#if defined(_WIN32)
#define MOJO_RAYLIB_EXPORT __declspec(dllexport)
#else
#define MOJO_RAYLIB_EXPORT __attribute__((visibility("default")))
#endif

typedef void (*mojo_trace_log_callback_simple)(int logLevel, const char *text);
static mojo_trace_log_callback_simple g_mojo_trace_log_callback = NULL;

static void mojo_trace_log_bridge(int logLevel, const char *text, va_list args)
{
    if (g_mojo_trace_log_callback == NULL) return;
    char buffer[2048] = { 0 };
    vsnprintf(buffer, sizeof(buffer), text, args);
    g_mojo_trace_log_callback(logLevel, buffer);
}

MOJO_RAYLIB_EXPORT void mojo_raylib_SetTraceLogCallback(mojo_trace_log_callback_simple callback)
{
    g_mojo_trace_log_callback = callback;
    SetTraceLogCallback((callback != NULL)? mojo_trace_log_bridge : NULL);
}

MOJO_RAYLIB_EXPORT void mojo_raylib_TraceLogLiteral(int logLevel, const char *text)
{
    TraceLog(logLevel, "%s", text);
}

MOJO_RAYLIB_EXPORT const char *mojo_raylib_TextFormatLiteral(const char *text)
{
    return TextFormat("%s", text);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Clamp(float value, float min, float max)
{
    return Clamp(value, min, max);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Lerp(float start, float end, float amount)
{
    return Lerp(start, end, amount);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Normalize(float value, float start, float end)
{
    return Normalize(value, start, end);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Remap(float value, float inputStart, float inputEnd, float outputStart, float outputEnd)
{
    return Remap(value, inputStart, inputEnd, outputStart, outputEnd);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Wrap(float value, float min, float max)
{
    return Wrap(value, min, max);
}

MOJO_RAYLIB_EXPORT int mojo_raymath_FloatEquals(float x, float y)
{
    return FloatEquals(x, y);
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2Zero()
{
    return Vector2Zero();
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2One()
{
    return Vector2One();
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2Add(Vector2 v1, Vector2 v2)
{
    return Vector2Add(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2AddValue(Vector2 v, float add)
{
    return Vector2AddValue(v, add);
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2Subtract(Vector2 v1, Vector2 v2)
{
    return Vector2Subtract(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2SubtractValue(Vector2 v, float sub)
{
    return Vector2SubtractValue(v, sub);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Vector2Length(Vector2 v)
{
    return Vector2Length(v);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Vector2LengthSqr(Vector2 v)
{
    return Vector2LengthSqr(v);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Vector2DotProduct(Vector2 v1, Vector2 v2)
{
    return Vector2DotProduct(v1, v2);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Vector2CrossProduct(Vector2 v1, Vector2 v2)
{
    return Vector2CrossProduct(v1, v2);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Vector2Distance(Vector2 v1, Vector2 v2)
{
    return Vector2Distance(v1, v2);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Vector2DistanceSqr(Vector2 v1, Vector2 v2)
{
    return Vector2DistanceSqr(v1, v2);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Vector2Angle(Vector2 v1, Vector2 v2)
{
    return Vector2Angle(v1, v2);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Vector2LineAngle(Vector2 start, Vector2 end)
{
    return Vector2LineAngle(start, end);
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2Scale(Vector2 v, float scale)
{
    return Vector2Scale(v, scale);
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2Multiply(Vector2 v1, Vector2 v2)
{
    return Vector2Multiply(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2Negate(Vector2 v)
{
    return Vector2Negate(v);
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2Divide(Vector2 v1, Vector2 v2)
{
    return Vector2Divide(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2Normalize(Vector2 v)
{
    return Vector2Normalize(v);
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2Transform(Vector2 v, Matrix mat)
{
    return Vector2Transform(v, mat);
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2Lerp(Vector2 v1, Vector2 v2, float amount)
{
    return Vector2Lerp(v1, v2, amount);
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2Reflect(Vector2 v, Vector2 normal)
{
    return Vector2Reflect(v, normal);
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2Min(Vector2 v1, Vector2 v2)
{
    return Vector2Min(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2Max(Vector2 v1, Vector2 v2)
{
    return Vector2Max(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2Rotate(Vector2 v, float angle)
{
    return Vector2Rotate(v, angle);
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2MoveTowards(Vector2 v, Vector2 target, float maxDistance)
{
    return Vector2MoveTowards(v, target, maxDistance);
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2Invert(Vector2 v)
{
    return Vector2Invert(v);
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2Clamp(Vector2 v, Vector2 min, Vector2 max)
{
    return Vector2Clamp(v, min, max);
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2ClampValue(Vector2 v, float min, float max)
{
    return Vector2ClampValue(v, min, max);
}

MOJO_RAYLIB_EXPORT int mojo_raymath_Vector2Equals(Vector2 p, Vector2 q)
{
    return Vector2Equals(p, q);
}

MOJO_RAYLIB_EXPORT Vector2 mojo_raymath_Vector2Refract(Vector2 v, Vector2 n, float r)
{
    return Vector2Refract(v, n, r);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3Zero()
{
    return Vector3Zero();
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3One()
{
    return Vector3One();
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3Add(Vector3 v1, Vector3 v2)
{
    return Vector3Add(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3AddValue(Vector3 v, float add)
{
    return Vector3AddValue(v, add);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3Subtract(Vector3 v1, Vector3 v2)
{
    return Vector3Subtract(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3SubtractValue(Vector3 v, float sub)
{
    return Vector3SubtractValue(v, sub);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3Scale(Vector3 v, float scalar)
{
    return Vector3Scale(v, scalar);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3Multiply(Vector3 v1, Vector3 v2)
{
    return Vector3Multiply(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3CrossProduct(Vector3 v1, Vector3 v2)
{
    return Vector3CrossProduct(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3Perpendicular(Vector3 v)
{
    return Vector3Perpendicular(v);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Vector3Length(const Vector3 v)
{
    return Vector3Length(v);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Vector3LengthSqr(const Vector3 v)
{
    return Vector3LengthSqr(v);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Vector3DotProduct(Vector3 v1, Vector3 v2)
{
    return Vector3DotProduct(v1, v2);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Vector3Distance(Vector3 v1, Vector3 v2)
{
    return Vector3Distance(v1, v2);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Vector3DistanceSqr(Vector3 v1, Vector3 v2)
{
    return Vector3DistanceSqr(v1, v2);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Vector3Angle(Vector3 v1, Vector3 v2)
{
    return Vector3Angle(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3Negate(Vector3 v)
{
    return Vector3Negate(v);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3Divide(Vector3 v1, Vector3 v2)
{
    return Vector3Divide(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3Normalize(Vector3 v)
{
    return Vector3Normalize(v);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3Project(Vector3 v1, Vector3 v2)
{
    return Vector3Project(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3Reject(Vector3 v1, Vector3 v2)
{
    return Vector3Reject(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3Transform(Vector3 v, Matrix mat)
{
    return Vector3Transform(v, mat);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3RotateByQuaternion(Vector3 v, Quaternion q)
{
    return Vector3RotateByQuaternion(v, q);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3RotateByAxisAngle(Vector3 v, Vector3 axis, float angle)
{
    return Vector3RotateByAxisAngle(v, axis, angle);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3MoveTowards(Vector3 v, Vector3 target, float maxDistance)
{
    return Vector3MoveTowards(v, target, maxDistance);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3Lerp(Vector3 v1, Vector3 v2, float amount)
{
    return Vector3Lerp(v1, v2, amount);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3CubicHermite(Vector3 v1, Vector3 tangent1, Vector3 v2, Vector3 tangent2, float amount)
{
    return Vector3CubicHermite(v1, tangent1, v2, tangent2, amount);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3Reflect(Vector3 v, Vector3 normal)
{
    return Vector3Reflect(v, normal);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3Min(Vector3 v1, Vector3 v2)
{
    return Vector3Min(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3Max(Vector3 v1, Vector3 v2)
{
    return Vector3Max(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3Barycenter(Vector3 p, Vector3 a, Vector3 b, Vector3 c)
{
    return Vector3Barycenter(p, a, b, c);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3Unproject(Vector3 source, Matrix projection, Matrix view)
{
    return Vector3Unproject(source, projection, view);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3Invert(Vector3 v)
{
    return Vector3Invert(v);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3Clamp(Vector3 v, Vector3 min, Vector3 max)
{
    return Vector3Clamp(v, min, max);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3ClampValue(Vector3 v, float min, float max)
{
    return Vector3ClampValue(v, min, max);
}

MOJO_RAYLIB_EXPORT int mojo_raymath_Vector3Equals(Vector3 p, Vector3 q)
{
    return Vector3Equals(p, q);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_Vector3Refract(Vector3 v, Vector3 n, float r)
{
    return Vector3Refract(v, n, r);
}

MOJO_RAYLIB_EXPORT Vector4 mojo_raymath_Vector4Zero()
{
    return Vector4Zero();
}

MOJO_RAYLIB_EXPORT Vector4 mojo_raymath_Vector4One()
{
    return Vector4One();
}

MOJO_RAYLIB_EXPORT Vector4 mojo_raymath_Vector4Add(Vector4 v1, Vector4 v2)
{
    return Vector4Add(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector4 mojo_raymath_Vector4AddValue(Vector4 v, float add)
{
    return Vector4AddValue(v, add);
}

MOJO_RAYLIB_EXPORT Vector4 mojo_raymath_Vector4Subtract(Vector4 v1, Vector4 v2)
{
    return Vector4Subtract(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector4 mojo_raymath_Vector4SubtractValue(Vector4 v, float add)
{
    return Vector4SubtractValue(v, add);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Vector4Length(Vector4 v)
{
    return Vector4Length(v);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Vector4LengthSqr(Vector4 v)
{
    return Vector4LengthSqr(v);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Vector4DotProduct(Vector4 v1, Vector4 v2)
{
    return Vector4DotProduct(v1, v2);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Vector4Distance(Vector4 v1, Vector4 v2)
{
    return Vector4Distance(v1, v2);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_Vector4DistanceSqr(Vector4 v1, Vector4 v2)
{
    return Vector4DistanceSqr(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector4 mojo_raymath_Vector4Scale(Vector4 v, float scale)
{
    return Vector4Scale(v, scale);
}

MOJO_RAYLIB_EXPORT Vector4 mojo_raymath_Vector4Multiply(Vector4 v1, Vector4 v2)
{
    return Vector4Multiply(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector4 mojo_raymath_Vector4Negate(Vector4 v)
{
    return Vector4Negate(v);
}

MOJO_RAYLIB_EXPORT Vector4 mojo_raymath_Vector4Divide(Vector4 v1, Vector4 v2)
{
    return Vector4Divide(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector4 mojo_raymath_Vector4Normalize(Vector4 v)
{
    return Vector4Normalize(v);
}

MOJO_RAYLIB_EXPORT Vector4 mojo_raymath_Vector4Min(Vector4 v1, Vector4 v2)
{
    return Vector4Min(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector4 mojo_raymath_Vector4Max(Vector4 v1, Vector4 v2)
{
    return Vector4Max(v1, v2);
}

MOJO_RAYLIB_EXPORT Vector4 mojo_raymath_Vector4Lerp(Vector4 v1, Vector4 v2, float amount)
{
    return Vector4Lerp(v1, v2, amount);
}

MOJO_RAYLIB_EXPORT Vector4 mojo_raymath_Vector4MoveTowards(Vector4 v, Vector4 target, float maxDistance)
{
    return Vector4MoveTowards(v, target, maxDistance);
}

MOJO_RAYLIB_EXPORT Vector4 mojo_raymath_Vector4Invert(Vector4 v)
{
    return Vector4Invert(v);
}

MOJO_RAYLIB_EXPORT int mojo_raymath_Vector4Equals(Vector4 p, Vector4 q)
{
    return Vector4Equals(p, q);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_MatrixDeterminant(Matrix mat)
{
    return MatrixDeterminant(mat);
}

MOJO_RAYLIB_EXPORT float mojo_raymath_MatrixTrace(Matrix mat)
{
    return MatrixTrace(mat);
}

MOJO_RAYLIB_EXPORT Matrix mojo_raymath_MatrixTranspose(Matrix mat)
{
    return MatrixTranspose(mat);
}

MOJO_RAYLIB_EXPORT Matrix mojo_raymath_MatrixInvert(Matrix mat)
{
    return MatrixInvert(mat);
}

MOJO_RAYLIB_EXPORT Matrix mojo_raymath_MatrixIdentity()
{
    return MatrixIdentity();
}

MOJO_RAYLIB_EXPORT Matrix mojo_raymath_MatrixAdd(Matrix left, Matrix right)
{
    return MatrixAdd(left, right);
}

MOJO_RAYLIB_EXPORT Matrix mojo_raymath_MatrixSubtract(Matrix left, Matrix right)
{
    return MatrixSubtract(left, right);
}

MOJO_RAYLIB_EXPORT Matrix mojo_raymath_MatrixMultiply(Matrix left, Matrix right)
{
    return MatrixMultiply(left, right);
}

MOJO_RAYLIB_EXPORT Matrix mojo_raymath_MatrixMultiplyValue(Matrix left, float value)
{
    return MatrixMultiplyValue(left, value);
}

MOJO_RAYLIB_EXPORT Matrix mojo_raymath_MatrixTranslate(float x, float y, float z)
{
    return MatrixTranslate(x, y, z);
}

MOJO_RAYLIB_EXPORT Matrix mojo_raymath_MatrixRotate(Vector3 axis, float angle)
{
    return MatrixRotate(axis, angle);
}

MOJO_RAYLIB_EXPORT Matrix mojo_raymath_MatrixRotateX(float angle)
{
    return MatrixRotateX(angle);
}

MOJO_RAYLIB_EXPORT Matrix mojo_raymath_MatrixRotateY(float angle)
{
    return MatrixRotateY(angle);
}

MOJO_RAYLIB_EXPORT Matrix mojo_raymath_MatrixRotateZ(float angle)
{
    return MatrixRotateZ(angle);
}

MOJO_RAYLIB_EXPORT Matrix mojo_raymath_MatrixRotateXYZ(Vector3 angle)
{
    return MatrixRotateXYZ(angle);
}

MOJO_RAYLIB_EXPORT Matrix mojo_raymath_MatrixRotateZYX(Vector3 angle)
{
    return MatrixRotateZYX(angle);
}

MOJO_RAYLIB_EXPORT Matrix mojo_raymath_MatrixScale(float x, float y, float z)
{
    return MatrixScale(x, y, z);
}

MOJO_RAYLIB_EXPORT Matrix mojo_raymath_MatrixFrustum(double left, double right, double bottom, double top, double nearPlane, double farPlane)
{
    return MatrixFrustum(left, right, bottom, top, nearPlane, farPlane);
}

MOJO_RAYLIB_EXPORT Matrix mojo_raymath_MatrixPerspective(double fovY, double aspect, double nearPlane, double farPlane)
{
    return MatrixPerspective(fovY, aspect, nearPlane, farPlane);
}

MOJO_RAYLIB_EXPORT Matrix mojo_raymath_MatrixOrtho(double left, double right, double bottom, double top, double nearPlane, double farPlane)
{
    return MatrixOrtho(left, right, bottom, top, nearPlane, farPlane);
}

MOJO_RAYLIB_EXPORT Matrix mojo_raymath_MatrixLookAt(Vector3 eye, Vector3 target, Vector3 up)
{
    return MatrixLookAt(eye, target, up);
}

MOJO_RAYLIB_EXPORT Quaternion mojo_raymath_QuaternionAdd(Quaternion q1, Quaternion q2)
{
    return QuaternionAdd(q1, q2);
}

MOJO_RAYLIB_EXPORT Quaternion mojo_raymath_QuaternionAddValue(Quaternion q, float add)
{
    return QuaternionAddValue(q, add);
}

MOJO_RAYLIB_EXPORT Quaternion mojo_raymath_QuaternionSubtract(Quaternion q1, Quaternion q2)
{
    return QuaternionSubtract(q1, q2);
}

MOJO_RAYLIB_EXPORT Quaternion mojo_raymath_QuaternionSubtractValue(Quaternion q, float sub)
{
    return QuaternionSubtractValue(q, sub);
}

MOJO_RAYLIB_EXPORT Quaternion mojo_raymath_QuaternionIdentity()
{
    return QuaternionIdentity();
}

MOJO_RAYLIB_EXPORT float mojo_raymath_QuaternionLength(Quaternion q)
{
    return QuaternionLength(q);
}

MOJO_RAYLIB_EXPORT Quaternion mojo_raymath_QuaternionNormalize(Quaternion q)
{
    return QuaternionNormalize(q);
}

MOJO_RAYLIB_EXPORT Quaternion mojo_raymath_QuaternionInvert(Quaternion q)
{
    return QuaternionInvert(q);
}

MOJO_RAYLIB_EXPORT Quaternion mojo_raymath_QuaternionMultiply(Quaternion q1, Quaternion q2)
{
    return QuaternionMultiply(q1, q2);
}

MOJO_RAYLIB_EXPORT Quaternion mojo_raymath_QuaternionScale(Quaternion q, float mul)
{
    return QuaternionScale(q, mul);
}

MOJO_RAYLIB_EXPORT Quaternion mojo_raymath_QuaternionDivide(Quaternion q1, Quaternion q2)
{
    return QuaternionDivide(q1, q2);
}

MOJO_RAYLIB_EXPORT Quaternion mojo_raymath_QuaternionLerp(Quaternion q1, Quaternion q2, float amount)
{
    return QuaternionLerp(q1, q2, amount);
}

MOJO_RAYLIB_EXPORT Quaternion mojo_raymath_QuaternionNlerp(Quaternion q1, Quaternion q2, float amount)
{
    return QuaternionNlerp(q1, q2, amount);
}

MOJO_RAYLIB_EXPORT Quaternion mojo_raymath_QuaternionSlerp(Quaternion q1, Quaternion q2, float amount)
{
    return QuaternionSlerp(q1, q2, amount);
}

MOJO_RAYLIB_EXPORT Quaternion mojo_raymath_QuaternionCubicHermiteSpline(Quaternion q1, Quaternion outTangent1, Quaternion q2, Quaternion inTangent2, float t)
{
    return QuaternionCubicHermiteSpline(q1, outTangent1, q2, inTangent2, t);
}

MOJO_RAYLIB_EXPORT Quaternion mojo_raymath_QuaternionFromVector3ToVector3(Vector3 from, Vector3 to)
{
    return QuaternionFromVector3ToVector3(from, to);
}

MOJO_RAYLIB_EXPORT Quaternion mojo_raymath_QuaternionFromMatrix(Matrix mat)
{
    return QuaternionFromMatrix(mat);
}

MOJO_RAYLIB_EXPORT Matrix mojo_raymath_QuaternionToMatrix(Quaternion q)
{
    return QuaternionToMatrix(q);
}

MOJO_RAYLIB_EXPORT Quaternion mojo_raymath_QuaternionFromAxisAngle(Vector3 axis, float angle)
{
    return QuaternionFromAxisAngle(axis, angle);
}

MOJO_RAYLIB_EXPORT Quaternion mojo_raymath_QuaternionFromEuler(float pitch, float yaw, float roll)
{
    return QuaternionFromEuler(pitch, yaw, roll);
}

MOJO_RAYLIB_EXPORT Vector3 mojo_raymath_QuaternionToEuler(Quaternion q)
{
    return QuaternionToEuler(q);
}

MOJO_RAYLIB_EXPORT Quaternion mojo_raymath_QuaternionTransform(Quaternion q, Matrix mat)
{
    return QuaternionTransform(q, mat);
}

MOJO_RAYLIB_EXPORT int mojo_raymath_QuaternionEquals(Quaternion p, Quaternion q)
{
    return QuaternionEquals(p, q);
}

MOJO_RAYLIB_EXPORT Matrix mojo_raymath_MatrixCompose(Vector3 translation, Quaternion rotation, Vector3 scale)
{
    return MatrixCompose(translation, rotation, scale);
}

